/**********************************************
* @file drive.h
* @author Tao Chen <chentao@oregonstate.edu>
* @date March 07, 2017
* @copyright 2017 Oregon State University
* @brief ROS node to drive the car following the path generated by move_base
*
* @details This node subscribes to /cmd_vel topic from local_base_plan (move_base)
*           then convert the /cmd_vel to chassis commands.
***********************************************/

#include <ros/ros.h>
#include <ros/time.h>
#include <nodelet/nodelet.h>
#include <autorally_msgs/chassisCommand.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/PoseStamped.h>
#include <nav_msgs/Odometry.h>
#include <std_msgs/Float64.h>
#include <math.h>

#define PI 3.14159265358979323846264338

namespace autorally_smartdriving{
  class Drive{
    public:
      Drive();
      ~Drive();

    private:
      ros::NodeHandle d_nh;
      ros::Subscriber d_driveSub;     //subscribe to /cmd_vel
      ros::Subscriber d_odomSub;      //subscribe to odom to get current pose
      ros::Subscriber d_goalSub;      //subscribe to current goal
      ros::Publisher d_drivePub;      //publish chassisCommand
      //ros::Publisher d_constSpeedPub; //publish speed commands to the constant speed controller 

      double goalX;         //initialy infinity
      double goalY;

      bool reached;

      void gatherVelData(geometry_msgs::Twist data);    //convert to chassis command
      void getCurrentGoal(geometry_msgs::PoseStamped);  //get the current goalY
      void gatherOdomData(nav_msgs::Odometry);          //get current position and compare it to the goal
      double AngleDiff(double a, double b);
      double Clamp(double num, double min, double max);
  };
};
